// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvdftnetinkhjrxkitnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZGZ0bmV0aW5raGpyeGtpdG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTk2MTUsImV4cCI6MjA1NTM3NTYxNX0.INFh8EqNV5T-_6-L1pHo2mdq5uI_rWCiSI9dKjY8yjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);